- name: Docker playbook
  hosts: instances
  gather_facts: yes
  any_errors_fatal: true
  become: true
  become_user: root

  pre_tasks:
    - name: update before starting installation
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: install ca-certificates curl
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: create a folder and set permission
      ansible.builtin.file:
        path: "/etc/apt/keyrings"
        state: directory
        owner: root
        group: root
        mode: 0755 

    - name: download docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: set permissioni for docker.asc
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add Docker's official repository to Apt sources
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: "docker"
        update_cache: yes

    - name: apt update
      become: yes
      ansible.builtin.apt:
        update_cache: yes

    - name: install docker and its plugins
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: add current user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

  post_tasks:
    - shell: echo "Docker installation is complete. Use 'docker --version' to verify."
